export default{
	state:{
		list:[
			{
				id:1,
				name:"柳博望",
				head:"柳",
				tel:"18816881688",
				address:{region:{"label":"甘肃省-兰州市-榆中县","value":[18,2,1],"cityCode":"440304"},
				detailed:'兰州大学榆中校区'},
				isDefault:true
			},
			{
				id:2,
				name:"李四",
				head:"李",
				tel:"18816881688",
				address:{region:{"label":"甘肃省-兰州市-榆中县","value":[18,2,1],"cityCode":"440304"},
				detailed:'兰州大学榆中校区'},
				isDefault:false
			}
		]
	},
	getters:{
		
	},
	muatations:{
		createPath(state,obj){
			state.list.unshift(obj);
		},
		//把之前选中的默认地址变成未选中地址
		removePath(state){
			state.list.forEach(v=>{
				if(isDefault){
					v.isDefault = false;
				}
			})
		}
	},
	actions:{
		createPathFn({commit},obj){
			if(obj.isDefault){
				commit("removePath");
			}
			commit('createPath',obj);
		}
	}	
}