export default {
	"state": {
		"1": "揽收",
		"101": "已下单",
		"102": "待揽收",
		"103": "已揽收",
		"0": "在途",
		"1001": "到达派件城市",
		"1002": "干线",
		"1003": "转递",
		"5": "派件",
		"501": "投柜或驿站",
		"3": "已签收",
		"301": "本人签收",
		"302": "派件异常后签收",
		"303": "代签",
		"304": "投柜或站签收",
		"6": "退回",
		"4": "退签",
		"401": "已销单",
		"14": "拒签",
		"7": "转投",
		"2": "疑难",
		"201": "超时未签收",
		"202": "超时未更新",
		"203": "拒收",
		"204": "派件异常",
		"205": "柜或驿站超时未取",
		"206": "无法联系",
		"207": "超区",
		"208": "滞留",
		"209": "破损",
		"8": "清关",
		"10": "待清关",
		"11": "清关中",
		"12": "已清关",
		"13": "清关异常",
		"\\": "收件人拒签",
	},
	"code": {
		"yuantong": "圆通速递",
		"yunda": "韵达快递",
		"shentong": "申通快递",
		"zhongtong": "中通快递",
		"youzhengguonei": "邮政快递包裹",
		"shunfeng": "顺丰速运",
		"ems": "EMS",
		"huitongkuaidi": "百世快递",
		"jtexpress": "极兔速递",
		"jd": "京东物流",
		"youzhengbk": "邮政标准快递",
		"fengwang": "丰网速运",
		"debangkuaidi": "德邦快递",
		"debangwuliu": "德邦",
		"yundakuaiyun": "韵达快运",
		"suer": "速尔快递",
		"emsbg": "EMS包裹",
		"zhongtongguoji": "中通国际",
		"zhongtongkuaiyun": "中通快运",
		"baishiwuliu": "百世快运",
		"zhaijisong": "宅急送",
		"lntjs": "特急送",
		"annengwuliu": "安能快运",
		"youzhengguoji": "国际包裹",
		"youshuwuliu": "优速快递",
		"ups": "UPS",
		"shunfengkuaiyun": "顺丰快运",
		"dhl": "DHL-中国件",
		"annto": "安得物流",
		"kuayue": "跨越速运",
		"yimidida": "壹米滴答",
		"dsukuaidi": "D速快递",
		"upsen": "UPS-全球件",
		"fedex": "FedEx-国际件",
		"rrs": "日日顺物流",
		"ewe": "EWE全球快递",
		"yuntrack": "YunExpress",
		"jinguangsudikuaijian": "京广速递",
		"lianhaowuliu": "联昊通",
		"longbanwuliu": "龙邦速递",
		"sxjdfreight": "顺心捷达",
		"danniao": "丹鸟",
		"timelytitan": "Titan泰坦国际速递",
		"usps": "USPS",
		"savor": "海信物流",
		"jiayunmeiwuliu": "加运美",
		"xinfengwuliu": "信丰物流",
		"dhlen": "DHL-全球件",
		"huisenky": "汇森速运",
		"disifang": "递四方",
		"cosco": "中远e环球",
		"stosolution": "申通国际",
		"jiuyescm": "九曳供应链",
		"wtdchina": "威时沛运货运",
		"shpost": "同城快寄",
		"suteng": "速腾快递",
		"yuxinwuliu": "宇鑫物流",
		"meiquick": "美快国际物流",
		"jingdongkuaiyun": "京东快运",
		"shunchangguoji": "顺昌国际",
		"japanposten": "日本（Japan Post）",
		"yw56": "燕文物流",
		"fedexcn": "Fedex-国际件-中文",
		"gotoubi": "UBI Australia",
		"btexpress": "邦泰快运",
		"zhongyouex": "众邮快递",
		"auexpress": "澳邮中国快运",
		"xlobo": "Xlobo贝海国际",
		"dpd": "DPD",
		"emsguoji": "EMS-国际件",
		"hd": "宏递快运",
		"tiantian": "天天快递",
		"chukou1": "出口易",
		"postnl": "荷兰邮政(PostNL international registered mail)",
		"ecmscn": "易客满",
		"suning": "苏宁物流",
		"santaisudi": "三态速递",
		"lahuoex": "拉火速运",
		"yuantongguoji": "圆通国际",
		"zhengyikuaidi": "鑫正一快递",
		"gls": "GLS",
		"chinaicip": "卓志速运",
		"lianbangkuaidi": "联邦快递",
		"subida": "速必达",
		"shenghuiwuliu": "盛辉物流",
		"tiandihuayu": "天地华宇",
		"tnt": "TNT",
		"doortodoor": "CJ物流",
		"koreapostcn": "韩国邮政",
		"sja56": "四季安物流",
		"goex": "时安达速递",
		"rlgaus": "澳洲飞跃物流",
		"ztky": "中铁快运",
		"wherexpess": "威盛快递",
		"dekuncn": "德坤物流",
		"tianma": "天马迅达",
		"dpdgermany": "DPD Germany",
		"zhimakaimen": "芝麻开门",
		"dpduk": "DPD UK",
		"quanyikuaidi": "全一快递",
		"ane66": "安能快递",
		"anxl": "安迅物流",
		"huolalawuliu": "货拉拉物流",
		"arkexpress": "方舟速递",
		"zhuanyunsifang": "转运四方",
		"nsf": "新顺丰（NSF）",
		"pingandatengfei": "平安达腾飞",
		"fujisuyun": "富吉速运",
		"ocs": "OCS",
		"ubonex": "优邦速运",
		"sut56": "速通物流",
		"jialidatong": "嘉里大通",
		"kejie": "科捷物流",
		"aotsd": "澳天速运",
		"sfwl": "盛丰物流",
		"sanhuwuliu": "叁虎物流",
		"japanpost": "日本郵便",
		"tnten": "TNT-全球件",
		"jinan": "金岸物流",
		"ftd": "富腾达国际货运",
		"jgwl": "景光物流",
		"qhxyyg": "雪域易购",
		"zhongtiewuliu": "中铁飞豹",
		"rokin": "荣庆物流",
		"kuaijiesudi": "快捷速递",
		"disifangus": "递四方美国",
		"banma": "斑马物流",
		"shangqiao56": "商桥物流",
		"epanex": "泛捷国际速递",
		"taijin": "泰进物流",
		"superb": "Superb Express",
		"crazyexpress": "疯狂快递",
		"newsway": "家家通快递",
		"zhongsukuaidi": "中速快递",
		"postnlcn": "荷兰邮政-中文(PostNL international registered mail)",
		"guotongkuaidi": "国通快递",
		"unitedex": "联合速运",
		"sagawa": "佐川急便",
		"purolator": "Purolator",
		"longcps": "加拿大龙行速运",
		"weitepai": "微特派",
		"sunjex": "新杰物流",
		"aramex": "Aramex",
		"bpost": "比利时（Bpost）",
		"auspost": "澳大利亚(Australia Post)",
		"tzky": "铁中快运",
		"erqianjia56": "贰仟家物流",
		"polarexpress": "极地快递",
		"xdexpress": "迅达速递",
		"aliexpress": "无忧物流",
		"aae": "AAE-中国件",
		"pjbest": "品骏快递",
		"dfwl": "达发物流",
		"yaofeikuaidi": "耀飞同城快递",
		"uszcn": "转运中国",
		"la911": "鼎润物流",
		"baitengwuliu": "百腾物流",
		"auod": "澳德物流",
		"anxindakuaixi": "安信达",
		"austa": "Austa国际速递",
		"ubuy": "德国优拜物流",
		"jiacheng": "佳成快递 ",
		"emsinten": "EMS-国际件-英文",
		"sxexpress": "三象速递",
		"tcat": "黑猫宅急便",
		"synship": "SYNSHIP快递",
		"adapost": "安达速递",
		"yuananda": "源安达",
		"huangmajia": "黄马甲",
		"shanhuodidi": "闪货极速达",
		"lijisong": "成都立即送",
		"zhaijibian": "宅急便",
		"hnht56": "鸿泰物流",
		"flyway": "程光快递",
		"huahanwuliu": "华翰物流",
		"emswuliu": "EMS物流",
		"datianwuliu": "大田物流",
		"morelink56": "MoreLink",
		"sendtochina": "速递中国",
		"nntengda": "腾达速递",
		"guangdongyouzhengwuliu": "广东邮政",
		"wanjiawuliu": "万家物流",
		"jiaxianwuliu": "嘉贤物流",
		"postserv": "中华邮政",
		"sdto": "速达通",
		"sanzhi56": "三志物流",
		"abcglobal": "全球快运",
		"zlink": "三真驿道",
		"youyou": "优优速递",
		"tstexp": "TST速运通",
		"changjiang": "长江国际速递",
		"xynyc": "新元国际",
		"fastgoexpress": "速派快递",
		"jumstc": "聚盟共建",
		"wondersyd": "中邮速递",
		"cyxfx": "小飞侠速递",
		"baifudongfang": "百福东方",
		"guexp": "全联速运",
		"lhexpressus": "联合速递",
		"exfresh": "安鲜达",
		"yuntong": "运通速运",
		"tntitaly": "TNT Italy",
		"ucs": "合众速递(UCS）",
		"lbex": "龙邦物流",
		"cccc58": "中集冷云",
		"anjie88": "安捷物流",
		"udalogistic": "韵达国际",
		"yujiawl": "宇佳物流",
		"beiou": "beiou express",
		"bsht": "百事亨通",
		"newzealand": "新西兰（New Zealand Post）",
		"tmwexpress": "明达国际速递",
		"ocpost": "OC-Post",
		"valueway": "美通",
		"yjhgo": "武汉优进汇",
		"highsince": "海欣斯快递",
		"chinapost": "中国邮政（CHINA POST）",
		"zdepost": "直德邮",
		"shunfenghk": "顺丰-繁体",
		"longfx": "LUCFLOW EXPRESS",
		"shunfengnl": "顺丰-荷兰",
		"gdkjk56": "快捷快物流",
		"jssdt56": "时达通",
		"transrush": "TransRush",
		"dpex": "DPEX",
		"xiyoug": "西游寄",
		"signedexpress": "签收快递",
		"uspscn": "USPSCN",
		"bazirim": "皮牙子快递",
		"yafengsudi": "亚风速递",
		"yongchangwuliu": "永昌物流",
		"zhongyouwuliu": "中邮物流",
		"feiyuanvipshop": "飞远配送",
		"canpost": "加拿大(Canada Post)",
		"ganzhongnengda": "能达速递",
		"ydhex": "YDH",
		"beebird": "锋鸟物流",
		"tnjex": "明通国际快递",
		"a2u": "A2U速递",
		"esinotrans": "中外运",
		"beckygo": "佰麒快递",
		"jiayiwuliu": "佳怡物流",
		"mlw": "美乐维冷链物流",
		"homecourier": "如家国际快递",
		"airpak": "airpak expresss",
		"hermes": "Hermes",
		"youban": "邮邦国际",
		"yuandun": "远盾物流",
		"zhonghuan": "中环快递",
		"lianbangkuaidien": "联邦快递-英文",
		"quanfengkuaidi": "全峰快递",
		"ztcce": "中途速递",
		"qexpress": "易达通快递",
		"qinyuan": "秦远物流",
		"yangbaoguo": "洋包裹",
		"postnlchina": "荷兰邮政-中国件",
		"canpostfr": "加拿大邮政",
		"cnexps": "CNE",
		"di5pll": "递五方云仓",
		"yizhengdasuyun": "一正达速运",
		"ckeex": "城晓国际快递",
		"deutschepost": "德国(Deutsche Post)",
		"fedexus": "FedEx-美国件",
		"newgistics": "Newgistics",
		"bjemstckj": "北京EMS",
		"coe": "COE",
		"yuntongkuaidi": "运通中港",
		"hdcexpress": "汇达物流",
		"httx56": "汇通天下物流",
		"dhlecommerce": "dhl小包",
		"bflg": "上海缤纷物流",
		"chengji": "城际快递",
		"sd138": "泰国138国际物流",
		"wanxiangwuliu": "万象物流",
		"aaacooper": "AAA Cooper Transportation",
		"hrex": "锦程快递",
		"easyexpress": "EASY EXPRESS",
		"express2global": "E2G速递",
		"sundarexpress": "顺达快递",
		"xyb2b": "行云物流",
		"spring56": "春风物流",
		"jiajiwuliu": "佳吉快运",
		"oneexpress": "一速递",
		"bangbangpost": "帮帮发",
		"yuanfeihangwuliu": "原飞航",
		"haidaibao": "海带宝",
		"xunsuexpress": "迅速快递",
		"kuaika": "快卡",
		"changwooair": "昌宇国际",
		"xiangdawuliu": "湘达物流",
		"renrenex": "人人转运",
		"nebuex": "星云速递",
		"chinastarlogistics": "华欣物流",
		"passerbyaexpress": "顺捷美中速递",
		"correosdees": "西班牙(Correos de Espa?a)",
		"hkpost": "中国香港(HongKong Post)",
		"dpdpoland": "DPD Poland",
		"youjia": "友家速递",
		"cd3fwl": "中迅三方",
		"com1express": "商壹国际物流",
		"gooday365": "日日顺智慧物联",
		"juding": "聚鼎物流",
		"chuanxiwuliu": "传喜物流",
		"huif56": "汇峰物流",
		"kuaidawuliu": "快达物流",
		"mosuda": "魔速达",
		"ttkeurope": "天天欧洲物流",
		"yousutongda": "优速通达",
		"cjkoreaexpress": "大韩通运",
		"csuivi": "法国(La Poste)",
		"guoeryue": "天天快物流",
		"tntau": "TNT Australia",
		"ynztsy": "黑猫同城送",
		"szuem": "联运通物流",
		"tykd": "天翼快递",
		"quanchuan56": "全川物流",
		"usa7ex": "美七国际快递",
		"uscbexpress": "易境达国际物流",
		"yuanchengwuliu": "远成物流",
		"benteng": "奔腾物流",
		"hpexpress": "海派国际速递",
		"ykouan": "洋口岸",
		"parcelforce": "英国大包、EMS（Parcel Force）",
		"yongbangwuliu": "永邦国际物流",
		"chronopostfren": "法国大包、EMS-英文(Chronopost France)",
		"ledaowuliu": "楽道物流",
		"nzzto": "新西兰中通",
		"qhxykd": "雪域快递",
		"yourscm": "雅澳物流",
		"yufeng": "御风速运",
		"ztong": "智通物流",
		"100mexpress": "百米快运",
		"chllog": "嘉荣物流",
		"fengtianexpress": "奉天物流",
		"dhlde": "DHL-德国件（DHL Deutschland）",
		"ftky365": "丰通快运",
		"jiachenexpress": "佳辰国际速递",
		"yujtong": "宇捷通",
		"zhongwaiyun": "中外运速递",
		"koreapost": "韩国（Korea Post）",
		"colissimo": "法国小包（colissimo）",
		"hac56": "瀚朝物流",
		"stonewzealand": "申通新西兰",
		"cdek": "CDEK",
		"gzanjcwl": "广州安能聚创物流",
		"meiguokuaidi": "美国快递",
		"shangda": "上大物流",
		"szshihuatong56": "世华通物流",
		"hengluwuliu": "恒路物流",
		"peixingwuliu": "陪行物流",
		"shanxijianhua": "山西建华",
		"ycgky": "远成快运",
		"zjcy56": "创运物流",
		"haihongwangsong": "海红网送",
		"quansu": "全速物流",
		"tollpriority": "Toll Priority(Toll Online)",
		"ytkd": "运通中港快递",
		"asendia": "阿森迪亚",
		"cdjx56": "捷祥物流",
		"emms": "澳州顺风快递",
		"haixingqiao": "海星桥快递",
		"huanqiu": "环球速运",
		"lingsong": "领送送",
		"ndwl": "南方传媒物流",
		"shunfenglengyun": "顺丰冷链",
		"zengyisudi": "增益速递",
		"boyol": "贝业物流",
		"dande56": "丹递56",
		"hkposten": "中国香港(HongKong Post)英文",
		"alog": "心怡物流",
		"ausexpress": "澳世速递",
		"cjqy": "长吉物流",
		"emsen": "EMS-英文",
		"euasia": "欧亚专线",
		"exsuda": "E速达",
		"jcsuda": "嘉诚速达",
		"jiajikuaidi": "佳吉快递",
		"nanjingshengbang": "晟邦物流",
		"thailand": "泰国邮政（Thailand Thai Post）",
		"trakpak": "TRAKPAK",
		"astexpress": "安世通快递",
		"cfss": "银雁专送",
		"flysman": "飞力士物流",
		"heimao56": "黑猫速运",
		"shipgce": "飞洋快递",
		"shunjiefengda": "顺捷丰达",
		"sinoairinex": "中外运空运",
		"supinexpress": "速品快递",
		"ytchengnuoda": "承诺达",
		"emirates": "阿联酋(Emirates Post)",
		"express7th": "7号速递",
		"heibaowuliu": "黑豹物流",
		"hkems": "云邮跨境快递",
		"shlindao": "林道国际快递",
		"wykjt": "51跨境通",
		"yzswuliu": "亚洲顺物流",
		"bdatong": "八达通",
		"dayangwuliu": "大洋物流",
		"efs": "EFS Post（平安快递）",
		"hjwl": "汇捷物流",
		"ibuy8": "爱拜物流",
		"jxfex": "集先锋快递",
		"njhaobo": "浩博物流",
		"pochta": "俄罗斯邮政(Russian Post)",
		"quanjitong": "全际通",
		"shunjieda": "顺捷达",
		"sunspeedy": "新速航",
		"sxhongmajia": "红马甲物流",
		"zhongtianwanyun": "中天万运",
		"zrtl": "中融泰隆",
		"amusorder": "amazon-国际订单",
		"chuangyi": "创一快递",
		"cloudlogistics365": "群航国际物流",
		"correos": "哥斯达黎加(Correos de Costa Rica)",
		"dongjun": "成都东骏物流",
		"dpexen": "Toll",
		"italiane": "意大利(Poste Italiane)",
		"kingfreight": "货运皇",
		"qbexpress": "秦邦快运",
		"rpx": "rpx",
		"ruidianyouzheng": "瑞典（Sweden Post）",
		"ukrpostcn": "乌克兰邮政包裹",
		"belgiumpost": "比利时(Belgium Post)",
		"cnspeedster": "速舟物流",
		"hlyex": "好来运",
		"hongywl": "红远物流",
		"htongexpress": "华通快运",
		"kaolaexpress": "考拉国际速递",
		"lasership": "LaserShip",
		"lsexpress": "6LS EXPRESS",
		"postnlpacle": "荷兰包裹(PostNL International Parcels)",
		"quansutong": "全速通",
		"sccod": "丰程物流",
		"suijiawuliu": "穗佳物流",
		"szdpex": "深圳DPEX",
		"yiqisong": "一起送",
		"anposten": "爱尔兰(An Post)",
		"bpostinter": "比利时国际(Bpost international)",
		"chengpei": "河北橙配",
		"cpsair": "华中快递",
		"feibaokuaidi": "飞豹快递",
		"feikangda": "飞康达",
		"gdqwwl": "全网物流",
		"globaltracktrace": "globaltracktrace",
		"gslhkd": "联合快递",
		"jdiex": "JDIEX",
		"lfexpress": "龙枫国际快递",
		"swisspost": "瑞士(Swiss Post)",
		"vnpost": "越南EMS(VNPost Express)",
		"xianglongyuntong": "祥龙运通物流",
		"yuanzhijiecheng": "元智捷诚",
		"ywexpress": "远为快递",
		"1ziton": "一智通",
		"360lion": "360 Lion Express",
		"amazoncnorder": "亚马逊中国订单",
		"bht": "BHT",
		"chronopostfra": "法国大包、EMS-法文（Chronopost France）",
		"decnlh": "德中快递",
		"edtexpress": "e直运",
		"fardarww": "颿达国际快递",
		"farlogistis": "泛远国际物流",
		"gts": "GTS快递",
		"jieborne": "捷邦物流",
		"jingshun": "景顺物流",
		"khzto": "柬埔寨中通",
		"pakistan": "巴基斯坦(Pakistan Post)",
		"postenab": "PostNord(Posten AB)",
		"quanritongkuaidi": "全日通",
		"scic": "中加国际快递",
		"stkd": "顺通快递",
		"tjkjwl": "泰实货运",
		"usasueexpress": "速翼快递",
		"wjkwl": "万家康物流",
		"xiangteng": "翔腾物流",
		"zsmhwl": "明辉物流",
		"abf": "ABF",
		"adp": "ADP国际快递",
		"asendiausa": "Asendia USA",
		"ccd": "次晨达物流",
		"cces": "CCES/国通快递",
		"cevalogistics": "CEVA Logistic",
		"dhlbenelux": "DHL Benelux",
		"fastontime": "加拿大联通快运",
		"gsm": "GSM",
		"hangrui": "上海航瑞货运",
		"haoxiangwuliu": "豪翔物流",
		"huanqiuabc": "中国香港环球快运",
		"jamaicapost": "牙买加（Jamaica Post）",
		"jieanda": "捷安达",
		"jindawuliu": "金大物流",
		"junfengguoji": "骏丰国际速递",
		"latvia": "拉脱维亚(Latvijas Pasts)",
		"lqht": "恒通快递",
		"maxeedexpress": "澳洲迈速快递",
		"stoexpress": "美国申通",
		"uluckex": "优联吉运",
		"yibangwuliu": "一邦速递",
		"yyexp": "西安运逸快递",
		"zhonghongwl": "中宏物流",
		"airgtc": "加拿大民航快递",
		"auvanda": "中联速递",
		"bangsongwuliu": "邦送物流",
		"bjqywl": "青云物流",
		"buytong": "百通物流",
		"cdxinchen56": "鑫宸物流",
		"cnair": "CNAIR",
		"colombia": "哥伦比亚(4-72 La Red Postal de Colombia)",
		"ctoexp": "泰国中通CTO",
		"dadaoex": "大道物流",
		"dechuangwuliu": "深圳德创物流",
		"epspost": "联众国际",
		"fanyukuaidi": "凡宇快递",
		"fedroad": "FedRoad 联邦转运",
		"gongsuda": "共速达",
		"hmus": "华美快递",
		"idamalu": "大马鹿",
		"india": "印度(India Post)",
		"jcex": "jcex",
		"lasy56": "林安物流",
		"ldxpres": "林道国际快递-英文",
		"littlebearbear": "小熊物流",
		"luckyfastex": "吉捷国际速递",
		"malaysiapost": "马来西亚小包（Malaysia Post(Registered)）",
		"mchy": "木春货运",
		"meitai": "美泰物流",
		"mingliangwuliu": "明亮物流",
		"parcelforcecn": "英国邮政大包EMS",
		"pfcexpress": "皇家物流",
		"polarisexpress": "北极星快运",
		"runhengfeng": "全时速运",
		"shenganwuliu": "圣安物流",
		"sufengkuaidi": "速风快递",
		"welogistics": "世航通运",
		"yatfai": "一辉物流",
		"yiex": "宜送物流",
		"zjstky": "苏通快运",
		"zsda56": "转瞬达集运",
		"adlerlogi": "德国雄鹰速递",
		"agopost": "全程快递",
		"anjiekuaidi": "青岛安捷快递",
		"aolau": "AOL澳通速递",
		"austria": "奥地利(Austrian Post)",
		"auvexpress": "AUV国际快递",
		"azerbaijan": "阿塞拜疆EMS(EMS AzerExpressPost)",
		"baishiguoji": "百世国际",
		"baishiyp": "百世云配",
		"bcwelt": "BCWELT",
		"belize": "伯利兹(Belize Postal)",
		"chronopostport": "Chronopost Portugal",
		"citylink": "City-Link",
		"dfpost": "达方物流",
		"eupackage": "易优包裹",
		"gaotieex": "高铁快运",
		"gatien": "Gati-英文",
		"gda": "安的快递",
		"gslexpress": "德尚国际速递",
		"hnfy": "飞鹰物流",
		"huoban": "兰州伙伴物流",
		"iceland": "冰岛(Iceland Post)",
		"jiajiatong56": "佳家通货运",
		"jintongkd": "劲通快递",
		"kcs": "KCS",
		"koreapostkr": "韩国邮政韩文",
		"krtao": "淘韩国际快递",
		"kuaijiewuliu": "快捷物流",
		"lineone": "一号线",
		"linex": "Linex",
		"luyao": "路遥物流",
		"lwe": "LWE",
		"malaysiaems": "马来西亚大包、EMS（Malaysia Post(parcel,EMS)）",
		"minghangkuaidi": "民航快递",
		"nlebv": "亚欧专线",
		"nmhuahe": "华赫物流",
		"omniva": "爱沙尼亚(Eesti Post)",
		"portugalctt": "葡萄牙（Portugal CTT）",
		"quantwl": "全通快运",
		"qzx56": "全之鑫物流",
		"rhtexpress": "睿和泰速运",
		"rrskx": "日日顺快线",
		"saiaodi": "赛澳递",
		"sccs": "SCCS",
		"shbwch": "杰响物流",
		"shipbyace": "王牌快递",
		"singpost": "新加坡小包(Singapore Post)",
		"tonghetianxia": "通和天下",
		"wandougongzhu": "豌豆物流",
		"winit": "万邑通",
		"wuyuansudi": "伍圆速递",
		"xinning": "新宁物流",
		"xipost": "西邮寄",
		"ydfexpress": "易达丰国际速递",
		"yodel": "YODEL",
		"zenzen": "三三国际物流",
		"zhongjiwuliu": "中技物流",
		"zhpex": "众派速递",
		"ztjieda": "泰捷达国际物流",
		"zy100": "中远快运",
		"adaexpress": "明大快递",
		"advancing": "安达信",
		"agility": "Agility Logistics",
		"ahdf": "德方物流",
		"ahkbps": "卡邦配送",
		"ajexpress": "捷记方舟",
		"ajlogistics": "澳捷物流",
		"alfatrex": "AlfaTrex",
		"amcnorder": "amazon-国内订单",
		"apgecommerce": "apgecommerce",
		"ariesfar": "艾瑞斯远",
		"bdcgcc": "BDC快递",
		"belpost": "白俄罗斯(Belpochta)",
		"biaojikuaidi": "彪记快递",
		"bluedart": "BlueDart",
		"borderguru": "BorderGuru",
		"botspost": "博茨瓦纳",
		"brt": "BRT",
		"bulgarian": "保加利亚（Bulgarian Posts）",
		"cambodia": "柬埔寨(Cambodia Post)",
		"canpar": "Canpar",
		"chinasqk": "SQK国际速递",
		"chnexp": "中翼国际物流",
		"chszhonghuanguoji": "CHS中环国际快递",
		"chunghwa56": "中骅物流",
		"city56": "城市映急",
		"cllexpress": "澳通华人物流",
		"cloudexpress": "CE易欧通国际速递",
		"clsp": "CL日中速运",
		"cncexp": "C&C国际速递",
		"cnpex": "CNPEX中邮快递",
		"cnup": "CNUP 中联邮",
		"comexpress": "邦通国际",
		"correios": "莫桑比克（Correios de Moçambique）",
		"cqxingcheng": "重庆星程快递",
		"csxss": "新时速物流",
		"czwlyn": "云南诚中物流",
		"dcs": "DCS",
		"deltec": "Deltec Courier",
		"dhlhk": "DHL HK",
		"dhlnetherlands": "DHL-荷兰（DHL Netherlands）",
		"dhlpoland": "DHL-波兰（DHL Poland）",
		"directlink": "Direct Link",
		"donghanwl": "东瀚物流",
		"dtdcindia": "DTDC India",
		"ecallturn": "E跨通",
		"ecfirstclass": "EC-Firstclass",
		"ecmsglobal": "ECMS Express",
		"eiffel": "艾菲尔国际速递",
		"eshunda": "俄顺达",
		"estafeta": "Estafeta",
		"estes": "Estes",
		"eta100": "易达国际速递",
		"etong": "E通速递",
		"euexpress": "EU-EXPRESS",
		"euguoji": "易邮国际",
		"europeanecom": "europeanecom",
		"eusacn": "优莎速运",
		"ezhuanyuan": "易转运",
		"fastway": "Fastway Ireland",
		"fbkd": "飞邦快递",
		"fedexuk": "FedEx-英国件（FedEx UK)",
		"fedexukcn": "FedEx-英国件",
		"feikuaida": "飞快达",
		"fenghuangkuaidi": "凤凰快递",
		"flashexpress": "Flash Express",
		"fourpxus": "四方格",
		"fsexp": "全速快递",
		"ge2d": "GE2D跨境物流",
		"gibraltar": "直布罗陀[英国]( Royal Gibraltar Post)",
		"gjwl": "冠捷物流 ",
		"goldjet": "高捷快运",
		"guangdongyongbang": "永邦快递",
		"guanting": "冠庭国际物流",
		"gxwl": "光线速递",
		"haypost": "亚美尼亚(Haypost-Armenian Postal)",
		"hlpgyl": "共联配",
		"hltop": "海联快递",
		"hongbeixin": "红背心",
		"hongpinwuliu": "宏品物流",
		"hrvatska": "克罗地亚（Hrvatska Posta）",
		"huaxiahuoyun": "华夏货运",
		"huilin56": "汇霖大货网",
		"huiqiangkuaidi": "汇强快递",
		"hyeship": "鸿远物流",
		"interjz": "捷运达快递",
		"iran": "伊朗（Iran Post）",
		"israelpost": "以色列(Israel Post)",
		"jiguang": "极光转运",
		"jinyuekuaidi": "晋越快递",
		"jjx888": "佳捷翔物流",
		"kxda": "凯信达",
		"lanbiaokuaidi": "蓝镖快递",
		"logistics": "華信物流WTO",
		"lutong": "鲁通快运",
		"luxembourg": "卢森堡(Luxembourg Post)",
		"maldives": "马尔代夫(Maldives Post)",
		"mapleexpress": "今枫国际快运",
		"minbangsudi": "民邦速递",
		"mjexp": "美龙快递",
		"mmlogi": "猛犸速递",
		"mrw": "MRW",
		"mxe56": "中俄速通（淼信）",
		"myhermes": "MyHermes",
		"nuoyaao": "偌亚奥国际快递",
		"ocaargen": "OCA Argentina",
		"pcaexpress": "PCA Express",
		"pdstow": "全球速递",
		"peru": "秘鲁(SERPOST)",
		"pioneer": "先锋国际快递",
		"postdanmarken": "丹麦(Post Denmark)",
		"qinling": "秦岭智能速运",
		"quantium": "Quantium",
		"quanxintong": "全信通快递",
		"republic": "叙利亚(Syrian Post)",
		"saiaodimmb": "赛澳递for买卖宝",
		"sanshengco": "三盛快递",
		"scsujiada": "速佳达快运",
		"sczpds": "速呈",
		"sfau": "澳丰速递",
		"sfpost": "曹操到",
		"shipsoho": "苏豪快递",
		"sinoex": "中外运速递-中文",
		"sofast56": "嗖一下同城快递",
		"southafrican": "南非（South African Post Office）",
		"speedpost": "新加坡EMS、大包(Singapore Speedpost)",
		"stzd56": "智德物流",
		"subaoex": "速豹",
		"sucmj": "特急便物流",
		"sujievip": "郑州速捷",
		"taimek": "天美快递",
		"taoplus": "淘布斯国际物流",
		"ueq": "UEQ快递",
		"uhi": "优海国际速递",
		"vietnam": "越南小包(Vietnam Posts)",
		"wlfast": "凡仕特物流",
		"xflt56": "蓝天物流",
		"xyjexpress": "西游寄速递",
		"yamaxunwuliu": "亚马逊中国",
		"yilingsuyun": "亿领速运",
		"yingchao": "英超物流",
		"yishunhang": "亿顺航",
		"yoseus": "优胜国际速递",
		"youlai": "邮来速递",
		"yunfeng56": "韵丰物流",
		"zhdwl": "众辉达物流",
		"zhongchuan": "众川国际",
		"zlxdjwl": "中粮鲜到家物流",
		"zsky123": "准实快运",
		"zteexpress": "ZTE中兴物流",
		"abxexpress_my": "ABX Express",
		"acommerce": "aCommerce",
		"acscourier": "ACS Courier",
		"adiexpress": "安达易国际速递",
		"adsone": "ADSone",
		"afghan": "阿富汗(Afghan Post)",
		"afl": "AFL",
		"aland": "奥兰群岛",
		"albania": "阿尔巴尼亚(Posta shqipatre)",
		"algeria": "Algeria",
		"alliedexpress": "ALLIED",
		"amazon_fba_swiship": "Swiship UK",
		"anjiatongcheng": "安家同城快运",
		"anjun_logistics": "Anjun Logistics",
		"anlexpress": "新干线快递",
		"anteraja": "Anteraja",
		"aosu": "澳速物流",
		"apc": "APC Postal Logistics",
		"aplus100": "美国汉邦快递",
		"arc": "ARC",
		"aruba": "阿鲁巴[荷兰]（Post Aruba）",
		"asendiahk": "Asendia HK",
		"auadexpress": "澳达国际物流",
		"auex": "澳货通",
		"ausbondexpress": "澳邦国际物流",
		"axexpress": "澳新物流",
		"bahrain": "巴林(Bahrain Post)",
		"bangladesh": "孟加拉国(EMS)",
		"baotongkd": "宝通快递",
		"baoxianda": "报通快递",
		"barbados": "巴巴多斯(Barbados Post)",
		"bee001": "蜜蜂速递",
		"beeexpress": "BEE express",
		"benin": "贝宁",
		"benniao": "笨鸟国际",
		"bester": "飛斯特",
		"bhutan": "不丹邮政 Bhutan Post",
		"bjxsrd": "鑫锐达",
		"bjytsywl": "远通盛源",
		"bljt56": "佰乐捷通",
		"bmlchina": "标杆物流",
		"bohei": "波黑(JP BH Posta)",
		"bolivia": "玻利维亚",
		"bosind": "堡昕德速递",
		"boxc": "BOXC",
		"bphchina": "速方(Sufast)",
		"bqcwl": "百千诚物流",
		"brazilposten": "巴西(Brazil Post/Correios)",
		"briems": "宏桥国际物流",
		"brunei": "文莱(Brunei Postal)",
		"buylogic": "Buylogic",
		"byht": "展勤快递",
		"caledonia": "新喀里多尼亚[法国](New Caledonia)",
		"camekong": "到了港",
		"cameroon": "喀麦隆(CAMPOST)",
		"campbellsexpress": "Campbell’s Express",
		"canhold": "能装能送",
		"cargolux": "卢森堡航空",
		"cbl": "CBL Logistica",
		"cbl_logistica": "CBL Logistics",
		"cbllogistics": "广州信邦",
		"cbo56": "钏博物流",
		"ceskaposta": "捷克（?eská po?ta）",
		"ceva": "CEVA Logistics",
		"cex": "城铁速递",
		"chengda": "成达国际速递",
		"chengtong": "城通物流",
		"chile": "智利(Correos Chile)",
		"chinapostcb": "中邮电商",
		"chinaqingguan": "荣通国际",
		"chinatzx": "同舟行物流",
		"cht361": "诚和通",
		"chunfai": "中国香港骏辉物流",
		"citysprint": "citysprint",
		"cnausu": "中澳速递",
		"cneulogistics": "中欧物流",
		"cnws": "中国翼",
		"collectplus": "Collect+",
		"corporatecouriers": "Corporate couriers logistics",
		"correo": "乌拉圭（Correo Uruguayo）",
		"correoargentino": "阿根廷(Correo Argentina)",
		"correosexpress": "Correos Express",
		"courierpost": "CourierPost",
		"couriersplease": "Couriers Please",
		"crossbox": "环旅快运",
		"cypruspost": "塞浦路斯(Cyprus Post)",
		"dachser": "DACHSER",
		"dasu": "达速物流",
		"ddotbase": "叮当同城",
		"delhivery": "Delhivery",
		"desworks": "澳行快递",
		"dfglobalex": "东风全球速递",
		"dhluk": "dhluk",
		"dianyi": "云南滇驿物流",
		"didasuyun": "递达速运",
		"dindon": "叮咚澳洲转运",
		"dingdong": "叮咚快递",
		"disifangau": "递四方澳洲",
		"djibouti": "吉布提",
		"djy56": "天翔东捷运",
		"donghong": "东红物流",
		"dotzot": "Dotzot",
		"dpd_ireland": "DPD Ireland",
		"dpe_express": "DPE Express",
		"driverfastgo": "老司机国际快递",
		"dsv": "DSV",
		"dt8ang": "德淘邦",
		"dtd": "DTD",
		"duodao56": "多道供应链",
		"dyexpress": "大亿快递",
		"ealceair": "东方航空物流",
		"echo": "Echo",
		"ecomexpress": "Ecom Express",
		"ecotransite": "东西E全运",
		"ecuador": "厄瓜多尔(Correos del Ecuador)",
		"edaeuexpress": "易达快运",
		"edragon": "龙象国际物流",
		"efspost": "EFSPOST",
		"egypt": "埃及（Egypt Post）",
		"ekart": "Ekart",
		"el56": "易联通达",
		"elta": "希腊包裹（ELTA Hellenic Post）",
		"eltahell": "希腊EMS（ELTA Courier）",
		"emiratesen": "阿联酋(Emirates Post)",
		"emonitoring": "波兰小包(Poczta Polska)",
		"emonitoringen": "波兰小包(Poczta Polska)",
		"emsluqu": "高考通知书",
		"emssouthafrica": "南非EMS",
		"emsukraine": "乌克兰EMS(EMS Ukraine)",
		"emsukrainecn": "乌克兰EMS-中文(EMS Ukraine)",
		"england": "英国(大包,EMS)",
		"equick_cn": "Equick China",
		"eripostal": "厄立特里亚",
		"est365": "东方汇",
		"eteenlog": "ETEEN专线",
		"ethiopia": "埃塞俄比亚(Ethiopian postal)",
		"ethiopian": "埃塞俄比亚(Ethiopian Post)",
		"eucnrail": "中欧国际物流",
		"eucpost": "德国 EUC POST",
		"europe8": "败欧洲",
		"exbtr": "飛斯特運通",
		"excocotree": "可可树美中速运",
		"expeditors": "Expeditors",
		"explorer56": "探路速运",
		"expressplus": "澳洲新干线快递",
		"fandaguoji": "颿达国际快递-英文",
		"fastway_nz": "Fastway New Zealand",
		"fastway_za": "Fastway South Africa",
		"fastzt": "正途供应链",
		"feihukuaidi": "飞狐快递",
		"fengyee": "丰羿",
		"fiji": "斐济(Fiji Post)",
		"finland": "芬兰(Itella Posti Oy)",
		"firstflight": "First Flight",
		"firstlogistics": "First Logistics",
		"flashexpressen": "Flash Express-英文",
		"flowerkd": "花瓣转运",
		"fox": "FOX国际快递",
		"freakyquick": "FQ狂派速递",
		"ftlexpress": "法翔速运",
		"fyex": "飞云快递系统",
		"gaticn": "Gati-中文",
		"gatikwe": "Gati-KWE",
		"gdct56": "广东诚通物流",
		"gdex": "GDEX",
		"gdrz58": "容智快运",
		"gdxp": "新鹏快递",
		"georgianpost": "格鲁吉亚(Georgian Pos）",
		"ghanapost": "加纳",
		"ghl": "环创物流",
		"ghtexpress": "GHT物流",
		"giztix": "GIZTIX",
		"global99": "全球特快",
		"gls_italy": "GLS Italy",
		"gml": "英脉物流",
		"gogox": "GOGOX",
		"gojavas": "gojavas",
		"grab": "Grab",
		"greenland": "格陵兰[丹麦]（TELE Greenland A/S）",
		"grivertek": "潍鸿",
		"gscq365": "哥士传奇速递",
		"gswtkd": "万通快递",
		"gtgogo": "GT国际快运",
		"gttexpress": "GTT EXPRESS快递",
		"guangdongtonglu": "广东通路",
		"guernsey": "根西岛",
		"guoshunda": "国顺达物流",
		"guosong": "国送快运",
		"guyana": "圭亚那",
		"gvpexpress": "宏观国际快递",
		"gzxingcheng": "贵州星程快递",
		"h66": "货六六",
		"haihongmmb": "海红for买卖宝",
		"haimengsudi": "海盟速递",
		"haiwaihuanqiu": "海外环球",
		"haizhongzhuanyun": "海中转运",
		"handboy": "汉邦国际速递",
		"hanfengjl": "翰丰快递",
		"hangyu": "航宇快递",
		"haoyoukuai": "好又快物流",
		"happylink": "开心快递",
		"hengrui56": "恒瑞物流",
		"hermes_de": "Hermes Germany",
		"hermesworld": "Hermesworld",
		"hexinexpress": "合心速递",
		"hgy56": "环国运物流",
		"hhair56": "华瀚快递",
		"hitaoe": "Hi淘易快递",
		"hjs": "猴急送",
		"hkeex": "飞豹速递",
		"hlkytj": "互联快运",
		"hnqst": "河南全速通",
		"hnssd56": "顺时达物流",
		"hnzqwl": "中强物流",
		"holisollogistics": "Holisol",
		"homexpress": "居家通",
		"honduras": "洪都拉斯",
		"hongjie": "宏捷国际物流",
		"hotwms": "皇家云仓",
		"hqtd": "环球通达 ",
		"hrbzykd": "卓烨快递",
		"hre": "高铁速递",
		"hsgtsd": "海硕高铁速递",
		"ht22": "海淘物流",
		"htwd": "华通务达物流",
		"huada": "华达快运",
		"huandonglg": "环东物流",
		"huaqikuaiyun": "华企快运",
		"humpline": "驼峰国际",
		"hungary": "匈牙利（Magyar Posta）",
		"hunterexpress": "hunter Express",
		"hutongwuliu": "户通物流",
		"hyk": "上海昊宏国际货物",
		"hyytes": "恒宇运通",
		"hzpl": "华航快递",
		"idada": "大达物流",
		"idexpress": "ID Express",
		"iex": "泛太优达",
		"iexpress": "iExpress",
		"igcaexpress": "无限速递",
		"ilogen": "logen路坚",
		"ilyang": "ILYANG",
		"imile": "iMile",
		"imlb2c": "艾姆勒",
		"indonesia": "印度尼西亚EMS(Pos Indonesia-EMS)",
		"indopaket": "INDOPAKET",
		"inposdom": "多米尼加（INPOSDOM – Instituto Postal Dominicano）",
		"inpost_paczkomaty": "InPost Paczkomaty",
		"interlink": "Interlink Express",
		"interparcel": "Interparcel",
		"iparcel": "UPS i-parcel",
		"italysad": "Italy SDA",
		"ixpress": "IXPRESS",
		"iyoungspeed": "驿扬国际速运",
		"janio": "janio",
		"jdexpressusa": "骏达快递",
		"jdpplus": "急递",
		"jerseypost": "泽西岛",
		"jet": "极兔国际",
		"jetexpressgroup": "澳速通国际速递",
		"jetexpresszh": "J&T Express",
		"jetstarexp": "捷仕",
		"jiajiawl": "加佳物流",
		"jiazhoumao": "加州猫速递",
		"jinchengwuliu": "锦程物流",
		"jinduan": "近端",
		"jisu": "冀速物流",
		"jiugong": "九宫物流",
		"jiujiuwl": "久久物流",
		"jiuyicn": "久易快递",
		"jixianda": "急先达",
		"jixiangyouau": "吉祥邮（澳洲）",
		"jne": "JNE",
		"jordan": "约旦(Jordan Post)",
		"jsexpress": "骏绅物流",
		"jtexpressmy": "J&T Express 马来西亚",
		"jtexpresssg": "J&T Express 新加坡",
		"jtexpressth": "J&T Express 泰国",
		"juwu": "聚物物流",
		"juzhongda": "聚中大",
		"kahaexpress": "Kaha Epress",
		"kazpost": "哈萨克斯坦(Kazpost)",
		"kenya": "肯尼亚(POSTA KENYA)",
		"kerryexpress": "Kerry Express",
		"kerrytj": "嘉里大荣物流",
		"keypon": "启邦国际物流",
		"kfwnet": "快服务",
		"kjde": "跨境直邮通",
		"kn": "Kuehne + Nagel",
		"koalaexp": "考拉速递",
		"koali": "番薯国际货运",
		"ksudi": "快速递",
		"kuai8": "快8速运",
		"kuaitao": "快淘快递",
		"kuaiyouda": "四川快优达速递",
		"kuehnenagel": "Kuehne+Nagel",
		"kurasi": "KURASI",
		"kyrgyzpost": "吉尔吉斯斯坦(Kyrgyz Post)",
		"kyue": "跨跃国际",
		"landmarkglobal": "Landmark Global",
		"lanhukuaidi": "蓝弧快递",
		"lao": "老挝(Lao Express) ",
		"laposte": "塞内加尔",
		"latviaen": "拉脱维亚(Latvijas Pasts)",
		"lbbk": "立白宝凯物流",
		"ldzy168": "两点之间",
		"ledaexpress": "乐达全球速递",
		"ledii": "乐递供应链",
		"leopard": "云豹国际货运",
		"lesotho": "莱索托(Lesotho Post)",
		"letseml": "美联快递",
		"lexship": "Laxship",
		"lgs": "lazada",
		"lianyun": "联运快递",
		"libanpost": "黎巴嫩(Liban Post)",
		"lionparcel": "Lion Parcel",
		"lishi": "丽狮物流",
		"lithuania": "立陶宛（Lietuvos pa?tas）",
		"lmfex": "良藤国际速递",
		"lnet": "新易泰",
		"longlangkuaidi": "隆浪快递",
		"longvast": "长风物流",
		"loomisexpress": "Loomis Express",
		"ltexp": "乐天速递",
		"ltparcel": "联通快递",
		"lubang56": "路邦物流",
		"luben": "陆本速递 LUBEN EXPRESS",
		"lundao": "论道国际物流",
		"luxembourgde": "卢森堡(Luxembourg Post)",
		"luxembourgfr": "卢森堡(Luxembourg Post)",
		"macao": "中国澳门(Macau Post)",
		"macedonia": "马其顿(Macedonian Post)",
		"maersk": "Maersk",
		"mailamericas": "mailamericas",
		"mailikuaidi": "麦力快递",
		"mailongdy": "迈隆递运",
		"mainfreight": "Mainfreight",
		"malta": "马耳他（Malta Post）",
		"mangguo": "芒果速递",
		"matkahuolto": "Matkahuolto",
		"mauritius": "毛里求斯(Mauritius Post)",
		"meibang": "美邦国际快递",
		"meidaexpress": "美达快递",
		"meixi": "美西快递",
		"mexico": "墨西哥（Correos de Mexico）",
		"mexicodenda": "Mexico Senda Express",
		"mhsy": "名航速运",
		"milkyway": "银河物流",
		"mol": "Mitsui OSK Lines",
		"moldova": "摩尔多瓦(Posta Moldovei)",
		"mongolpost": "蒙古国(Mongol Post) ",
		"montenegro": "黑山(Posta Crne Gore)",
		"morocco": "摩洛哥 ( Morocco Post )",
		"multipack": "Mexico Multipack",
		"nalexpress": "新亚物流",
		"namibia": "纳米比亚(NamPost)",
		"nandan": "NandanCourier",
		"nationex": "Nationex",
		"nedahm": "红马速递",
		"nederlandpost": "荷兰速递(Nederland Post)",
		"nell": "尼尔快递",
		"nepalpost": "尼泊尔（Nepal Postal Services）",
		"networkcourier": "Network Courier",
		"nigerianpost": "尼日利亚(Nigerian Postal)",
		"ninjavan": "Ninja Van ",
		"ninjaxpress": "ninja xpress",
		"nipponexpress": "Nippon Express",
		"niuzaiexpress": "牛仔速运",
		"nle": "NLE",
		"norsk_global": "Norsk Global",
		"novaposhta": "Nova Poshta",
		"nuoer": "诺尔国际物流",
		"nyk": "NYK Line",
		"ocsindia": "﻿OCS ANA Group",
		"oman": "阿曼(Oman Post)",
		"omni2": "无限配",
		"omniparcel": "Omni Parcel",
		"onehcang": "一号仓",
		"oneworldexpress": "One World Express",
		"ontrac": "OnTrac",
		"onway": "昂威物流",
		"opek": "OPEK",
		"overseaex": "波音速递",
		"packlink": "Packlink",
		"panama": "巴拿马",
		"pandulogistics": "Pandu Logistics",
		"paraguay": "巴拉圭(Correo Paraguayo)",
		"parcel2go": "parcel2go",
		"parcelchina": "诚一物流",
		"parknparcel": "Park N Pracel",
		"paxel": "paxel",
		"paxelen": "paxelen",
		"pcwl56": "普畅物流",
		"peex": "派尔快递",
		"peisihuoyunkuaidi": "配思货运",
		"pengcheng": "鹏程快递",
		"pengyuanexpress": "鹏远国际速递",
		"pflogistics": "Parcel Freight Logistics",
		"phlpost": "菲律宾（Philippine Postal）",
		"pickupp": "pickupp",
		"pinsuxinda": "品速心达快递",
		"pinxinkuaidi": "品信快递",
		"pmt0704be": "龙行天下",
		"portugalctten": "葡萄牙（Portugal CTT）",
		"portugalseur": "Portugal Seur",
		"posindonesia": "POS INDONESIA",
		"posta": "坦桑尼亚（Tanzania Posts Corporation）",
		"postelbe": "PostElbe",
		"postennorge": "挪威（Posten Norge）",
		"postnord": "PostNord Logistics",
		"postpng": "巴布亚新几内亚(PNG Post)",
		"primamulticipta": "PT Prima Multi Cipta",
		"ptt": "土耳其",
		"pzhjst": "急顺通",
		"qdants": "ANTS EXPRESS",
		"qesd": "7E速递",
		"qianli": "千里速递",
		"qichen": "启辰国际速递",
		"qpost": "卡塔尔（Qatar Post）",
		"qskdyxgs": "千顺快递",
		"qxpress": "Qxpress",
		"ramgroup_za": "RAM",
		"redexpress": "Red Express",
		"redur": "Redur",
		"redur_es": "Redur Spain",
		"riyuwuliu": "日昱物流",
		"rl_carriers": "RL Carriers",
		"romanian": "罗马尼亚（Posta Romanian）",
		"royal": "皇家国际速运",
		"rrthk": "日日通国际",
		"ruidianyouzhengen": "瑞典（Sweden Post）",
		"runbail": "润百特货",
		"rwanda": "卢旺达(Rwanda i-posita)",
		"s2c": "S2C",
		"safexpress": "Safexpress",
		"sagawaen": "佐川急便-英文",
		"salvador": "Correo El Salvador",
		"samoa": "萨摩亚(Samoa Post)",
		"sapexpress": "SAP EXPRESS",
		"saudipost": "沙特阿拉伯(Saudi Post)",
		"scglogistics": "SCG",
		"scxingcheng": "四川星程快递",
		"sdsy888": "首达速运",
		"selektvracht": "Selektvracht",
		"sendinglog": "森鼎国际物流",
		"sendle": "Sendle",
		"serbia": "塞尔维亚(PE Post of Serbia)",
		"seur": "International Seur",
		"sfc": "SFC",
		"sfcservice": "SFC Service",
		"sfift": "十方通物流",
		"sfjhd": "圣飞捷快递",
		"shadowfax": "Shadowfax",
		"shanda56": "衫达快运",
		"shangcheng": "尚橙物流",
		"shanghaikuaitong": "上海快通",
		"shanghaiwujiangmmb": "上海无疆for买卖宝",
		"shangtuguoji": "尚途国际货运",
		"shaoke": "捎客物流",
		"shd56": "商海德物流",
		"shengtongscm": "盛通快递",
		"shenjun": "神骏物流",
		"shenma": "神马快递",
		"shiningexpress": "阳光快递",
		"shiyunkuaidi": "世运快递",
		"shlexp": "SHL畅灵国际物流",
		"shpostwish": "wish邮",
		"shreeanjanicourier": "shreeanjanicourier",
		"shunbang": "顺邦国际物流",
		"shunshid": "顺士达速运",
		"sicepat": "SiCepat Ekspres",
		"sihaiet": "四海快递",
		"sihiexpress": "四海捷运",
		"siodemka": "Siodemka",
		"sixroad": "易普递",
		"skynet": "skynet",
		"skynetmalaysia": "SkyNet Malaysia",
		"skynetworldwide": "skynetworldwide",
		"skypost": "荷兰Sky Post",
		"skypostal": "Asendia HK (LATAM)",
		"slovak": "斯洛伐克(Slovenská Posta)",
		"slovenia": "斯洛文尼亚(Slovenia Post)",
		"slpost": "斯里兰卡(Sri Lanka Post)",
		"solomon": "所罗门群岛",
		"sonapost": "布基纳法索",
		"speeda": "行必达",
		"speedoex": "申必达",
		"spoton": "Spoton",
		"ssd": "速速达",
		"staky": "首通快运",
		"starex": "星速递",
		"staryvr": "星运快递",
		"stlucia": "圣卢西亚",
		"sucheng": "速呈宅配",
		"sudapost": "苏丹（Sudapost）",
		"superoz": "速配欧翼",
		"surpost": "苏里南",
		"svgpost": "圣文森特和格林纳丁斯",
		"swaziland": "斯威士兰",
		"swiship": "Amazon FBA Swiship",
		"swisspostcn": "瑞士邮政",
		"sypost": "顺友物流",
		"szyouzheng": "深圳邮政",
		"tanzania": "坦桑尼亚(Tanzania Posts)",
		"taote": "淘特物流快递",
		"tcixps": "TCI XPS",
		"tcxbthai": "GPI",
		"tdcargo": "TD Cargo",
		"thebluebhellcouriers": "The BlueBhell Couriers",
		"thecourierguy": "The Courier Guy",
		"thunderexpress": "加拿大雷霆快递",
		"tianxiang": "天翔快递",
		"tianzong": "天纵物流",
		"tiki": "TiKi",
		"timedg": "万家通快递",
		"tipsa": "TIPSA",
		"tirupati": "Shree Tirupati",
		"tjlyz56": "老扬州物流",
		"tlky": "天联快运",
		"tmg": "株式会社T.M.G",
		"tntpostcn": "TNT Post",
		"tntuk": "TNT UK",
		"tny": "TNY物流",
		"togo": "多哥",
		"tongdaxing": "通达兴物流",
		"topshey": "顶世国际物流",
		"topspeedex": "中运全速",
		"tpcindia": "The Professional Couriers",
		"trackparcel": "track-parcel",
		"transkargologistics": "Trans Kargo",
		"tunisia": "突尼斯EMS(Rapid-Poste)",
		"turtle": "海龟国际快递",
		"tywl99": "天翼物流",
		"ubx": "UBX",
		"uex": "UEX国际物流",
		"uexiex": "欧洲UEX",
		"uganda": "乌干达(Posta Uganda)",
		"ugoexpress": "邮鸽速运",
		"ukraine": "乌克兰小包、大包(UkrPoshta)",
		"ukrpost": "乌克兰小包、大包(UkrPost)",
		"uniexpress": "Uni Express",
		"uparcel": "UParcel",
		"upsfreight": "UPS Freight",
		"upsmailinno": "UPS Mail Innovations",
		"uschuaxia": "华夏国际速递",
		"utaoscm": "UTAO优到",
		"uzbekistan": "乌兹别克斯坦(Post of Uzbekistan)",
		"vangenexpress": "万庚国际速递",
		"vanuatu": "瓦努阿图(Vanuatu Post)",
		"vctrans": "越中国际物流",
		"vipexpress": "鹰运国际速递",
		"vps": "维普恩物流",
		"wahana": "Wahana",
		"wanboex": "万博快递",
		"wanjiatong": "宁夏万家通",
		"wdm": "万达美",
		"wedepot": "wedepot物流",
		"wenjiesudi": "文捷航空",
		"westwing": "西翼物流",
		"wexpress": "威速递",
		"whgjkd": "香港伟豪国际物流",
		"whistl": "Whistl",
		"wln": "万理诺物流",
		"wlwex": "星空国际",
		"wotu": "渥途国际速运",
		"wowexpress": "wowexpress",
		"wowvip": "沃埃家",
		"wtdex": "WTD海外通",
		"wto56kj": "臣邦同城",
		"wuliuky": "五六快运",
		"wygj168": "万运国际快递",
		"wzhaunyun": "微转运",
		"xdshipping": "国晶物流",
		"xhf56": "鑫宏福物流",
		"xianchengliansudi": "西安城联速递",
		"xilaikd": "西安喜来快递",
		"xingyuankuaidi": "新元快递",
		"xpertdelivery": "Xpert Delivery",
		"xpressbees": "XpressBees",
		"xsrd": "鑫世锐达",
		"xtb": "鑫通宝物流",
		"xunxuan": "迅选物流",
		"xyd666": "鑫远东速运",
		"ycgglobal": "YCG物流",
		"ydglobe": "云达通",
		"yemen": "也门(Yemen Post)",
		"yhtlogistics": "宇航通物流",
		"yidatong": "易达通",
		"yidihui": "驿递汇速递",
		"yifankd": "艺凡快递",
		"yihangmall": "易航物流",
		"yikonn": "yikonn",
		"yinjiesudi": "银捷速递",
		"yiouzhou": "易欧洲国际物流",
		"yiqiguojiwuliu": "一柒国际物流",
		"yisong": "宜送",
		"yitongda": "易通达",
		"yiyou": "易邮速运",
		"yjs": "益加盛快递",
		"youyibang": "邮驿帮高铁速运",
		"ypsd": "壹品速递",
		"ytky168": "运通快运",
		"yuanhhk": "远航国际快运",
		"yue777": "玥玛速运",
		"yuefengwuliu": "越丰物流",
		"yuezhongsh": "粤中国际货运代理（上海）有限公司",
		"yundaexus": "美国云达",
		"yusen": "Yusen Logistics",
		"yyqc56": "一运全成物流",
		"zampost": "赞比亚",
		"zf365": "珠峰速运",
		"zhaojin": "招金精炼",
		"zhiguil": "智谷特货",
		"zhitengwuliu": "志腾物流",
		"zhonghuanus": "中环转运",
		"zhongxinda": "忠信达",
		"zhuoshikuaiyun": "卓实快运",
		"zjgj56": "振捷国际货运",
		"zyzoom": "增速跨境 ",
	}
}
